sudo: false
language: node_js
node_js:
- '4'
env:
  global:
  - SAUCE_USERNAME=elastic
  - SAUCE_ACCESS_KEY=de42e589-1450-41a2-8a44-90aa00c15168
  matrix:
  - MODE=saucelabs
cache:
  directories:
  - node_modules
addons:
  firefox: '38.0'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
